<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.11" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.16.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Behaviors\" />
    <Folder Include="FlashSales\" />
    <Folder Include="Interfaces\Repositories\" />
    <Folder Include="Products\Commands\" />
    <Folder Include="Products\DTOs\" />
    <Folder Include="Products\Queries\" />
    <Folder Include="Recommendations\" />
    <Folder Include="Orders\" />
  </ItemGroup>

</Project>
