<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Domain</RootNamespace>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <!-- Dam bao tat ca file .cs trong Entities, Enums, Common duoc bien dich vao assembly -->
  <ItemGroup>
    <Compile Include="Common\**\*.cs" />
    <Compile Include="Entities\**\*.cs" />
    <Compile Include="Enums\**\*.cs" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Helpers\RoleHelper.cs" />
    <Compile Include="Interfaces\Repositories\IBrandRepository.cs" />
    <Compile Include="Interfaces\Repositories\ICartRepository.cs" />
    <Compile Include="Interfaces\Repositories\ICategoryRepository.cs" />
    <Compile Include="Interfaces\Repositories\ICouponRepository.cs" />
    <Compile Include="Interfaces\Repositories\IInventoryRepository.cs" />
    <Compile Include="Interfaces\Repositories\IProductRepository.cs" />
    <Compile Include="Interfaces\Repositories\IPromotionRepository.cs" />
    <Compile Include="Interfaces\Repositories\IRoleRepository.cs" />
    <Compile Include="Interfaces\Repositories\IUserRepository.cs" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Events\" />
    <Folder Include="Specifications\" />
  </ItemGroup>

</Project>
